// <auto-generated />
using API.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AdSetContext))]
    partial class AdSetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entidades.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VeiculoID");

                    b.HasKey("Id")
                        .HasName("PK__Foto__3214EC27478B8C5E");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("API.Entidades.Opcional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Opcional__3214EC27101B7AB8");

                    b.ToTable("Opcional");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Ar Condicionado"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Airbag"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Freios ABS"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Alarme"
                        });
                });

            modelBuilder.Entity("API.Entidades.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.HasKey("Id")
                        .HasName("PK__Pacote__3214EC278F1A74BF");

                    b.HasIndex("PortalId");

                    b.ToTable("Pacote");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Básico",
                            PortalId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bronze",
                            PortalId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Platinum",
                            PortalId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Diamante",
                            PortalId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Básico",
                            PortalId = 2
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Bronze",
                            PortalId = 2
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Platinum",
                            PortalId = 2
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Diamante",
                            PortalId = 2
                        });
                });

            modelBuilder.Entity("API.Entidades.Portal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PK__Portal__3214EC27AF26D932");

                    b.ToTable("Portal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "iCarros"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Webmotors"
                        });
                });

            modelBuilder.Entity("API.Entidades.RelacaoVeiculoOpcional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OpcionalId")
                        .HasColumnType("int")
                        .HasColumnName("OpcionalID");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VeiculoID");

                    b.HasKey("Id")
                        .HasName("PK__RelacaoV__3214EC276129C2AB");

                    b.HasIndex("OpcionalId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("RelacaoVeiculoOpcional");
                });

            modelBuilder.Entity("API.Entidades.RelacaoVeiculoPacotePortal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PacoteId")
                        .HasColumnType("int")
                        .HasColumnName("PacoteID");

                    b.Property<int>("PortalId")
                        .HasColumnType("int")
                        .HasColumnName("PortalID");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VeiculoID");

                    b.HasKey("Id")
                        .HasName("PK__RelacaoV__3214EC27769DCE51");

                    b.HasIndex("PacoteId");

                    b.HasIndex("PortalId");

                    b.HasIndex(new[] { "VeiculoId", "PortalId" }, "UQ_Veiculo_Portal")
                        .IsUnique();

                    b.ToTable("RelacaoVeiculoPacotePortal");
                });

            modelBuilder.Entity("API.Entidades.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Veiculo__3214EC27C8994EF0");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("API.Entidades.Foto", b =>
                {
                    b.HasOne("API.Entidades.Veiculo", "Veiculo")
                        .WithMany("Foto")
                        .HasForeignKey("VeiculoId")
                        .IsRequired()
                        .HasConstraintName("FK_Foto_Veiculo");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("API.Entidades.Pacote", b =>
                {
                    b.HasOne("API.Entidades.Portal", "Portal")
                        .WithMany("Pacote")
                        .HasForeignKey("PortalId")
                        .IsRequired()
                        .HasConstraintName("FK_Pacote_Portal");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("API.Entidades.RelacaoVeiculoOpcional", b =>
                {
                    b.HasOne("API.Entidades.Opcional", "Opcional")
                        .WithMany("RelacaoVeiculoOpcional")
                        .HasForeignKey("OpcionalId")
                        .IsRequired()
                        .HasConstraintName("FK_RelacaoVeiculoOpcional_Opcional");

                    b.HasOne("API.Entidades.Veiculo", "Veiculo")
                        .WithMany("RelacaoVeiculoOpcional")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RelacaoVeiculoOpcional_Veiculo");

                    b.Navigation("Opcional");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("API.Entidades.RelacaoVeiculoPacotePortal", b =>
                {
                    b.HasOne("API.Entidades.Pacote", "Pacote")
                        .WithMany("RelacaoVeiculoPacotePortal")
                        .HasForeignKey("PacoteId")
                        .IsRequired()
                        .HasConstraintName("FK_RelacaoVeiculoPacotePortal_Pacote");

                    b.HasOne("API.Entidades.Portal", "Portal")
                        .WithMany("RelacaoVeiculoPacotePortal")
                        .HasForeignKey("PortalId")
                        .IsRequired()
                        .HasConstraintName("FK_RelacaoVeiculoPacotePortal_Portal");

                    b.HasOne("API.Entidades.Veiculo", "Veiculo")
                        .WithMany("RelacaoVeiculoPacotePortal")
                        .HasForeignKey("VeiculoId")
                        .IsRequired()
                        .HasConstraintName("FK_RelacaoVeiculoPacotePortal_Veiculo");

                    b.Navigation("Pacote");

                    b.Navigation("Portal");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("API.Entidades.Opcional", b =>
                {
                    b.Navigation("RelacaoVeiculoOpcional");
                });

            modelBuilder.Entity("API.Entidades.Pacote", b =>
                {
                    b.Navigation("RelacaoVeiculoPacotePortal");
                });

            modelBuilder.Entity("API.Entidades.Portal", b =>
                {
                    b.Navigation("Pacote");

                    b.Navigation("RelacaoVeiculoPacotePortal");
                });

            modelBuilder.Entity("API.Entidades.Veiculo", b =>
                {
                    b.Navigation("Foto");

                    b.Navigation("RelacaoVeiculoOpcional");

                    b.Navigation("RelacaoVeiculoPacotePortal");
                });
#pragma warning restore 612, 618
        }
    }
}
